// <auto-generated />
namespace Projet_T_T.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initialmigration3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialmigration3));
        
        string IMigrationMetadata.Id
        {
            get { return "202304030739011_initialmigration3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
